package com.Core.Question17;

public class MultipleCatchBlock {

        public static void main(String[] args) {

            try{
                int a[]=new int[5];
                a[5]=30/0;
               System.out.println(a);
            }
            catch(ArithmeticException e)
            {
                System.out.println("Arithmetic Exception occurs");
            }
            catch(ArrayIndexOutOfBoundsException e)
            {
                System.out.println("ArrayIndexOutOfBounds Exception occurs");
            }
            catch(Exception e)
            {
                System.out.println("Parent Exception occurs");
            }
            finally{
                int a=5;   //finally block executed
                int b=6;
                int c=a+b;
                System.out.println(c);
            }
         }
    }

